---
# tasks file for base-config
- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes
